<a href="https://colab.research.google.com/github/footvaalvica/machinelearninghomeworks/blob/main/hw3/hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import numpy as np

observations = (0.8, 1, 1.2, 1.4, 1.6)
targets = (24, 20, 10, 13, 12)

# Learn the Ridge regression (𝑙2 regularization) on the transformed data space using the closed
# form solution with 𝜆 = 2.
def ridge_regression(x, y, l):
    # Transform the data space
    x = np.array([[1, x[i], x[i]**2, x[i]**3] for i in range(len(x))])
    print("x: \n", x)
    # print(x)
    # Compute the closed form solution
    w = np.linalg.inv(x.T @ x + l * np.identity(x.shape[1])) @ x.T @ y  
    return w

# find weights
w = ridge_regression(observations, targets, 2)

# round values in w
w = np.round(w, 6)
print(w)

x: 
 [[1.    0.8   0.64  0.512]
 [1.    1.    1.    1.   ]
 [1.    1.2   1.44  1.728]
 [1.    1.4   1.96  2.744]
 [1.    1.6   2.56  4.096]]
[ 7.045076  4.640928  1.96734  -1.300881]


In [40]:
# Compute the training RMSE for the learnt regression model.
def rmse(x, y, w):
    # Transform the data space
    x = np.array([[1, x[i], x[i]**2, x[i]**3] for i in range(len(x))])
    # Compute RMSE
    rmse = np.sqrt(np.sum((x @ w - y)**2) / len(x))
    return rmse

# Compute the training RMSE
rmse = rmse(observations, targets, w)
print(round(rmse, 6))

6.843295
