<a href="https://colab.research.google.com/github/footvaalvica/machinelearninghomeworks/blob/main/hw3/hw3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
observations = (0.8, 1, 1.2, 1.4, 1.6)
targets = (24, 20, 10, 13, 12)

# Learn the Ridge regression (𝑙2 regularization) on the transformed data space using the closed
# form solution with 𝜆 = 2.
def ridge_regression(x, y, l):
    # Transform the data space
    x = np.array([[1, x[i], x[i]**2, x[i]**3] for i in range(len(x))])
    array = np.linalg.inv(x.T @ x + l * np.identity(x.shape[1]))
    # round the result to 3 decimal places and print it
    print(np.round(array, 4))


    w = np.linalg.inv(x.T @ x + l * np.identity(x.shape[1])) @ x.T @ y  
    print(x @ w)

    return np.round(w, 4)

# find weights
w = ridge_regression(observations, targets, 2)

# round values in w
w = np.round(w, 6)
print(w)

[[ 0.3417 -0.1214 -0.0749 -0.0093]
 [-0.1214  0.3892 -0.0967 -0.0745]
 [-0.0749 -0.0967  0.3726 -0.1714]
 [-0.0093 -0.0745 -0.1714  0.18  ]]
[11.35086463 12.35246259 13.19923625 13.8287433  14.17854143]
[ 7.0451  4.6409  1.9673 -1.3009]


In [15]:
# Compute the training RMSE for the learnt regression model.
x = np.array([[1, observations[i], observations[i]**2, observations[i]**3] for i in range(len(observations))])
z = targets
z_hat = x @ w

print(z_hat)

print(w)
sum = w[0]*np.array([1,1,1,1,1]) + w[1]*np.array([0.8,1,1.2,1.4,1.6]) + w[2]*np.array([0.8**2,1**2,1.2**2,1.4**2,1.6**2]) + w[3]*np.array([0.8**3,1**3,1.2**3,1.4**3,1.6**3])
print(sum)
def rmse(z, z_hat):
    # Compute the RMSE
    rmse = np.sqrt(1/len(z) * np.sum((z - z_hat)**2))
    
    # round the result to 3 decimal places and print it
    return rmse

# Compute the training RMSE
rmse = rmse(z, z_hat)
print("Final Result: ", round(rmse, 6))

[11.3508312 12.3524    13.1991368 13.8285984 14.1783416]
[ 7.0451  4.6409  1.9673 -1.3009]
[11.3508312 12.3524    13.1991368 13.8285984 14.1783416]
Final Result:  6.843296
